version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: python -m pip install --upgrade pip 
      - run: python -m pip install --upgrade virtualenv
      - python/install-packages:
          pip-dependency-file: dev-requirements.txt
          pkg-manager: pip
      - run:
          name: Test
          command: |
            python -m tox --skip-missing-interpreters
      - store_artifacts:
          path: htmlcov


workflows:
  main:
    jobs:
      - build-and-test